const install = require('express').Router();
const login = require('./login');
const add = require('./add');
const getbranchbytoken = require('./getbranchbytoken');
const getrolebytoken = require('./getrolebytoken');
const getfullrolebytoken = require('./getfullrolebytoken');
const updaterolebyroleid = require('./updaterolebyroleid');
const deleterole = require('./deleterole');
const insertrole = require('./insertrole');
const addlinkauto = require('./addlinkauto');
install.post('/login', login);
install.get('/add', add);
install.post('/getbranchbytoken', getbranchbytoken);
install.post('/getrolebytoken', getrolebytoken);
install.post('/getfullrolebytoken', getfullrolebytoken);
install.post('/updaterolebyroleid', updaterolebyroleid);
install.post('/insertrole', insertrole);
install.post('/deleterole', deleterole);
install.post('/addlinkauto', addlinkauto);
module.exports = install;
